# Generated by Django 5.1.2 on 2025-04-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreE', models.CharField(max_length=100)),
                ('entrenador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJ', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=50)),
                ('supertecnica', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='IEWikiapp01.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVideojuego', models.CharField(max_length=200)),
                ('plataforma', models.CharField(choices=[('NDS', 'Nintendo DS'), ('N3DS', 'Nintendo 3DS'), ('WII', 'Nintendo Wii')], max_length=5)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEWikiapp01.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEWikiapp01.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='VideojuegoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEWikiapp01.equipo')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEWikiapp01.videojuego')),
            ],
        ),
    ]
