# Generated by Django 5.1.2 on 2025-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='entrenador2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
