# Generated by Django 5.1.2 on 2025-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0002_equipo_entrenador2'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.CharField(default='/static/brain.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
