# Generated by Django 5.1.2 on 2025-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0003_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagenJ',
            field=models.CharField(default='http://127.0.0.1:8000/static/mark.jpeg', max_length=500),
            preserve_default=False,
        ),
    ]
