# Generated by Django 5.1.2 on 2025-05-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0004_jugador_imagenj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='equipo',
            new_name='equipoJ',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='posicion',
            new_name='posicionJ',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='supertecnica',
            new_name='supertecnicaJ',
        ),
    ]
