# Generated by Django 5.1.2 on 2025-05-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0005_rename_equipo_jugador_equipoj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
