# Generated by Django 5.1.2 on 2025-06-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokenSessions',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipoJ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEWikiapp01.equipo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=130),
        ),
    ]
