# Generated by Django 5.1.2 on 2025-06-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0007_user_tokensessions_alter_jugador_equipoj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEWikiapp01.jugador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEWikiapp01.user')),
            ],
        ),
    ]
