# Generated by Django 5.1.2 on 2025-06-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0008_meta_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'jugador')},
        ),
    ]
