# Generated by Django 5.1.2 on 2025-06-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0009_delete_meta_alter_like_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
