# Generated by Django 5.1.2 on 2025-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEWikiapp01', '0010_remove_user_name_remove_user_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supertecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
